package com.bao.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class TOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_0.order_id
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_0.user_id
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order_0.order_name
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    private String orderName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_0.order_id
     *
     * @return the value of t_order_0.order_id
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_0.order_id
     *
     * @param orderId the value for t_order_0.order_id
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_0.user_id
     *
     * @return the value of t_order_0.user_id
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_0.user_id
     *
     * @param userId the value for t_order_0.user_id
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order_0.order_name
     *
     * @return the value of t_order_0.order_name
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order_0.order_name
     *
     * @param orderName the value for t_order_0.order_name
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName == null ? null : orderName.trim();
    }
}