package com.bao.model;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_0.id
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_0.user_id
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_0.name
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_0.age
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_0.id
     *
     * @return the value of t_user_0.id
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_0.id
     *
     * @param id the value for t_user_0.id
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_0.user_id
     *
     * @return the value of t_user_0.user_id
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_0.user_id
     *
     * @param userId the value for t_user_0.user_id
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_0.name
     *
     * @return the value of t_user_0.name
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_0.name
     *
     * @param name the value for t_user_0.name
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_0.age
     *
     * @return the value of t_user_0.age
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_0.age
     *
     * @param age the value for t_user_0.age
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}