server:
  port: 9003


eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /heath
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  zipkin:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
#          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 20000
management:
  security:
    enabled: false
