server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
#    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000

spring:
  application:
    name: ms-eureka