server:
  port: 9006


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


# not effect
#feign:
#  hystrix:
#    enabled: false

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
spring:
  application:
    name: ms-gateway
logging:
  level:
    root: debug
