server:
  port: 9004

eureka:
  instance:
    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
  client:
#    region: default
#    registryFetchIntervalSeconds: 5
#    availabilityZones:
#      default: ${APPLICATION_DOMAIN:${DOMAIN:defaultZone}}
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ypp-oauth
    username: root
    password: root123~


#logging:
#  level:
#    com.netflix.discovery: 'OFF'

