package com.bao.msdatasources.mapper;

import com.bao.msdatasources.config.DataBaseSelector;
import com.bao.msdatasources.model.TOrder;
import org.apache.ibatis.annotations.Mapper;

@DataBaseSelector(name = "test1")
@Mapper
public interface TOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    int insert(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    int insertSelective(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    TOrder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    int updateByPrimaryKeySelective(TOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_0
     *
     * @mbg.generated Wed Mar 15 22:35:41 CST 2017
     */
    int updateByPrimaryKey(TOrder record);
}