package com.bao.mapper;

import com.bao.model.User;
import org.apache.ibatis.annotations.Mapper;


@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_0
     *
     * @mbg.generated Sun Mar 12 21:51:46 CST 2017
     */
    int updateByPrimaryKey(User record);
}